export const GAMES = {
  bomkusJam: {
    name: 'Dr. Bomkus Game Jam - Energy Run',
    user: 'AlamayaStudios',
    rating: '5.0',
    quests: '',
    visits: '101',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/bomkusJam.avif', import.meta.url).href,
  },
  subvox: {
    name: 'SUBVOX',
    user: 'theJoncrow',
    rating: '5.0',
    quests: '',
    visits: '42',
    mode: 'Single Player',
    label: 'Premium',
    img: new URL('./assets/game-img/subvox.avif', import.meta.url).href,
  },
  bang: {
    name: 'TheBang',
    user: 'addy2045',
    rating: '4.7',
    quests: '',
    visits: '100',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/bang.avif', import.meta.url).href,
  },
  scb: {
    name: 'SCB 10X HQ: Social Hub',
    user: 'SCB10X',
    rating: '4.5',
    quests: '15',
    visits: '1K',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/scb.avif', import.meta.url).href,
  },
  trend: {
    name: 'TRENDY FACTORY',
    user: 'Gikis',
    rating: '4.7',
    quests: '',
    visits: '255',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/trend-factory.webp', import.meta.url).href,
  },
  shadows: {
    name: 'Shadows Untold: BLOOD ISLAND',
    user: 'LUCIDITYUK',
    rating: '4.3',
    quests: '',
    visits: '107',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/shadows.webp', import.meta.url).href,
  },
  aave: {
    name: 'Aavegotchi - Ripples Of The Gotchiverse',
    user: 'PixelCraftStudios',
    rating: '4.4',
    quests: '30',
    visits: '1K',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/aave.png', import.meta.url).href,
  },
  cuddle: {
    name: 'CUDDLE CITADEL',
    user: 'VauxMachinaStudios',
    rating: '',
    quests: '',
    visits: '27',
    mode: 'Single Player',
    label: 'Premium',
    img: new URL('./assets/game-img/cuddle.avif', import.meta.url).href,
  },
  bomkus: {
    name: 'Bomkus Brutal company',
    user: 'Sandja',
    rating: '4.0',
    quests: '',
    visits: '67',
    mode: 'Single Player',
    label: 'Premium',
    img: new URL('./assets/game-img/bomkus.png', import.meta.url).href,
  },
  dogami: {
    name: 'DOGAMÍ - DOGA CITY',
    user: 'DOGAMI222',
    rating: '5.0',
    quests: '',
    visits: '429',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/dogami.png', import.meta.url).href,
  },
  rainbow: {
    name: 'Rainbow Bridge : The Ascend',
    user: 'TapNation',
    rating: '4.3',
    quests: '',
    visits: '148',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/rainbow.webp', import.meta.url).href,
  },
  floor: {
    name: 'Floor Droppers by MetaWorlds & Metatheory Studio + Partners!',
    user: 'Lanzrr',
    rating: '4.9',
    quests: '',
    visits: '167',
    mode: 'MultiPlayer',
    label: 'Premium',
    img: new URL('./assets/game-img/floor.png', import.meta.url).href,
  },
  help: {
    name: '-Hello, Help Us!',
    user: 'MetaguildStudio',
    rating: '4.5',
    quests: '9',
    visits: '5K',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/help.avif', import.meta.url).href,
  },
  car: {
    name: 'JDM garage car experience from Tokyo',
    user: 'blind975',
    rating: '',
    quests: '',
    visits: '',
    mode: 'Singleplayer',
    label: '',
    img: new URL('./assets/game-img/car.avif', import.meta.url).href,
  },
  olcHK: {
    name: 'One Last Chance (Hong Kong Edition)',
    user: 'thehiddenwalls',
    rating: '',
    quests: '',
    visits: '',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/olchk.avif', import.meta.url).href,
  },
  olcMeta: {
    name: 'One Last Chance (Metaverse Central Edition)',
    user: 'thehiddenwalls',
    rating: '',
    quests: '',
    visits: '',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/olcmt.avif', import.meta.url).href,
  },
  olcVox: {
    name: 'One Last Chance (Voxel Madness Edition)',
    user: 'thehiddenwalls',
    rating: '',
    quests: '',
    visits: '',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/olcvx.avif', import.meta.url).href,
  },
  olcGalleria: {
    name: 'One Last Chance (Galleria Edition)',
    user: 'thehiddenwalls',
    rating: '5.0',
    quests: '',
    visits: '',
    mode: 'Single Player',
    label: '',
    img: new URL('./assets/game-img/olcg.avif', import.meta.url).href,
  },
  hue: {
    name: 'Hue Hustle',
    user: 'CyberDragonGames',
    rating: '',
    quests: '',
    visits: '9',
    mode: 'MultiPlayer',
    label: '',
    img: new URL('./assets/game-img/hue.avif', import.meta.url).href,
  },
}
